### ISSUE TITLE
VPS mining prohibited?

### ISSUE THREAD

**Issue by Traxo7** [jvanname/circcash#1]
https://github.com/jvanname/circcash/wiki/Circcash-bounties-for-week-8:30-to-9:5

> Be the first entity besides the core developer to set up a node using a cloud computing service such as Digital Ocean, and keep the node running constantly at least until another entity besides the core developer has set up a node using a cloud computing service.

(I realize that the status of the bounty is "closed". Not concerned with that.)  

But just wanted to share what Digital Ocean support told me:  

> Unfortunately mining is against our Terms and Conditions (12.1 Termination and Access), please see here: https://www.digitalocean.com/legal/terms-of-service-agreement/
> Violating these terms would result in account termination.  

EDIT:  
Just in case the response was ambiguous, they clarified that the restriction applies to dedicated servers as well:  
> Unfortunately yes, even on optimised Droplets.  Really sorry for the inconvenience!

**Comment by jvanname** [comment]
Another miner told me about another cloud computing provider Hetzner which also discontinued the mining service. As a result, since the week 8:30-9:5 is over, I have removed the reference to this bounty along with all my Digital Ocean references that I could find. I still have my Digital Ocean node up to help other nodes connect to the network but this node is no longer mining. If these cloud computing service providers would have read up on Circcash, they would have realized that Circcash mining is made to improve the services that cloud computing service providers provide in the long term.
